project:
  type: website
  output-dir: docs

website:
  title: "Romain Boutelet"
  site-url: "https://www.romainboutelet.github.io/"
  navbar:
    background: $green
    left:
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: contact.qmd
        text: Contact
    right: 
      - icon: github
        href: https://github.com/romainboutelet
        aria-label: GitHub
        target: "_blank"
        rel: "noopener noreferrer"
      - icon: envelope-at
        href: mailto:boutelet@msu.edu

format:
  html:
    theme:
      - cosmo
      - assets/styles.scss
    css: styles.css
    toc: true

editor: visual

